apiVersion: apps/v1
kind: Deployment  
metadata:  
  name: redirect-1
  namespace: tst1
  labels:
    app: redirect-1
spec:  
  selector:
    matchLabels:
      app: redirect-1
  template:
    metadata:  
      labels:  
        app: redirect-1
    spec:
      nodeSelector:
         "beta.kubernetes.io/os":  linux
      containers:  
      - name: redirect-1
        image: 'farzadjalali/k8s-routing:latest'
        ports:   
        - containerPort: 80
--- 
apiVersion: v1
kind: Service 
metadata: 
  name: redirect-1-service
  namespace: tst1
spec: 
  type: LoadBalancer
  ports: 
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http-port
  selector: 
    app: redirect-1

